name: 'Send notification'
description: 'Sends a notification about failure to Slack'
inputs:
  secret:
    description: 'Slack hook URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send notifications
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "emrzv-test",
            "text": ":x: The ij-perf-report-aggregator/${{ github.workflow }}/${{ github.job }} job has failed on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}|${{ inputs.commit_message }}>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.secret }}
