name: 'Send notification'
description: 'Sends a notification about failure to Slack'
inputs:
  secret:
    description: 'Slack hook URL'
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "emrzv-test",
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.secret }}
