name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: This step can fail
        id: can-fail
        run: exit 1

      - uses: ./.github/send-notification
        if: ${{ failure() }}
        with:
          workflow_name: ${{ github.workflow }}
          job_name: ${{ github.job }}
          run_id: ${{ github.run_id }}
          commit_message: ${{ github.event.head_commit.message }}
          secret: ${{ secrets.SLACK_WEBHOOK_URL }}
