name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: This step can fail
        id: can-fail
        run: exit 1

      - name: Send notifications
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        with:
          payload: |
            {
              "channel": "ij-starter-github-failures",
              "text": |
                :x: The workflow has failed on
                <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.event.head_commit.message }}>
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
