name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: This step can fail
        id: can-fail
        run: exit 1

      - uses: emrzv/github-test-actions/.github/workflows/send-notifications.yml
        if: ${{ failure() }}
        with:
          workflow-name: github.action
          job-name: job.name
          run-id: github.run_id
          commit-message: github.event.head_commit.message
