name: CI

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      job_name:
        required: true
        type: string
      run_id:
        required: true
        type: string
      commit_message:
        required: true
        type: string

jobs:
  send_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Send notifications
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "phpstorm-support-ex",
              "text": ":x: The ij-perf-report-aggregator/${{ inputs.workflow_name }}/${{ inputs.job_name }} has failed on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}|${{ inputs.commit_message }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
